
spring:  
  jpa:  
    hibernate:  
      ddl-auto: update 
    showsql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
  datasource:  
    url: "jdbc:postgresql://localhost:5432/postgres"  
    username: fawwazuddin
    password: fawwaz@123
 
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub	

springdoc-swagger-ui:
  path : /swagger-ui.html
springdoc:
  api-docs :
    path : /api-docs  